### ISSUE TITLE
让btn组件防抖更精准

### ISSUE THREAD

**Issue by 1003657663** [chengxg/cxg-arduino-lib#1]
我是用esp32，接了一个按键开关。长按的时候，每隔几十个低电压就会出现一个高电压，不知道为啥，所以按键的按下和抬起事件会不断的抖动。我写了一个方法来规避这个问题。我觉得这个方法对于没有这个问题的按键设备也可以用上。有备无患。

`activeQueue[0] = activeQueue[1];
  activeQueue[1] = activeQueue[2];
  activeQueue[2] = activeQueue[3];
  activeQueue[3] = isActiveTmp;

  isActive = activeQueue[0];
  for (int i = 1; i < 4; i++)
  {
    if (activeQueue[i] != isActive)
    {
      return;
    }
  }`

代码大致就是上面这样，连续4个相同的active才算是正常的active，中间出现抖动，就抛弃掉。

**Comment by chengxg** [comment]
非常感谢指出问题, 我写这个只是满足自己的需要, 目前我主要从事web前端开发, 对单片机方面只是兴趣.
关于按键抖动的问题, 我倒是用的不多, 没怎么 遇到过, 这个问题我猜测可能是按钮本身的问题, 或者手按住按钮时用力不均导致的接触不良,或者按钮没加上拉下拉电阻导致的, 不知用的是不是微动开关.
不知调整一下按钮的这几个参数有没有效果
&nbsp;&nbsp;unsigned&nbsp;int&nbsp;btnLongPressInterval&nbsp;=&nbsp;200;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//长按间隔时间,&nbsp;每过一段时间触发一次长按回调
&nbsp;&nbsp;unsigned&nbsp;int&nbsp;btnLongPressTriggerTime&nbsp;=&nbsp;2000;&nbsp;&nbsp;//长按触发时间
&nbsp;&nbsp;unsigned&nbsp;int&nbsp;btnDoubleTriggerTime&nbsp;=&nbsp;800;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//双击触发时间,&nbsp;在这个时间内点击下一次就触发双击
&nbsp;&nbsp;unsigned&nbsp;int&nbsp;btnDebounceTime&nbsp;=&nbsp;20;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;//按键防抖延时时间






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chengxg/cxg-arduino-lib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 凌晨1:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chengxg/cxg-arduino-lib] 让btn组件防抖更精准 (#1)





 
我是用esp32，接了一个按键开关。长按的时候，每隔几十个低电压就会出现一个高电压，不知道为啥，所以按键的按下和抬起事件会不断的抖动。我写了一个方法来规避这个问题。我觉得这个方法对于没有这个问题的按键设备也可以用上。有备无患。
 
`activeQueue[0] = activeQueue[1];
 activeQueue[1] = activeQueue[2];
 activeQueue[2] = activeQueue[3];
 activeQueue[3] = isActiveTmp;
 
isActive = activeQueue[0];
 for (int i = 1; i < 4; i++)
 {
 if (activeQueue[i] != isActive)
 {
 return;
 }
 }`
 
代码大致就是上面这样，连续4个相同的active才算是正常的active，中间出现抖动，就抛弃掉。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1003657663** [comment]
我也是做前端开发的，哈哈。用的就是普通的微动开关，按钮默认用10k上拉电阻上拉，按下按钮是用10k电阻下拉，但还是不断的在0,1之间跳动，没办法了，使用4次的相同的状态判断为最终状态这个方案，效果非常好。

你那个jsTime我用上了，很好用！
